services:
    mongo:
        image: mongo:latest
        container_name: mongo
        restart: always
        volumes:
            - mongo_data:/data/db
        ports:
            - "27017:27017"

    backend:
        image: mwajahat/my-backend:latest
        container_name: backend
        restart: always
        environment:
            - MONGO_URI=mongodb://mongo:27017/todos
            - PORT=5000
        ports:
            - "5000:5000"
        depends_on:
            - mongo

    frontend:
        image: mwajahat/my-frontend:latest
        container_name: frontend
        restart: always
        ports:
            - "3000:80"
        depends_on:
            - backend

volumes:
    mongo_data:
